export const POST_NEW_USER = 'POST_NEW_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const GET_SIGNED_IN_USER = 'GET_SIGNED_IN_USER';
export const GET_SPECIFIC_USER = 'GET_SPECIFIC_USER';
export const GET_SEARCHED_USERS = 'GET_SEARCHED_USERS';
export const SET_LOGGED_IN_USER = 'SET_LOGGED_IN_USER';
export const EDIT_USER_PROFILE = 'EDIT_USER_PROFILE';

export const GET_SEARCHED_BOOKS = 'GET_SEARCHED_BOOKS';
export const GET_SPECIFIC_BOOK = 'GET_SPECIFIC_BOOK';
export const GET_CURRENT_BOOK = 'GET_CURRENT_BOOK';
export const POST_BOOK_LIKE = 'POST_BOOK_LIKE';
export const DELETE_BOOK_LIKE = 'DELETE_BOOK_LIKE';

export const GET_ARTICLES = 'GET_ARTICLES';
export const POST_ARTICLE = 'POST_ARTICLE';
export const GET_SPECIFIC_ARTICLE = 'GET_SPECIFIC_ARTICLE';
export const EDIT_SPECIFIC_ARTICLE = 'EDIT_SPECIFIC_ARTICLE';
export const DELETE_SPECIFIC_ARTICLE = 'DELETE_SPECIFIC_ARTICLE';
export const GET_ARTICLE_LIKE = 'GET_ARTICLE_LIKE';
export const POST_ARTICLE_LIKE = 'POST_ARTICLE_LIKE';
export const DELETE_ARTICLE_LIKE = 'DELETE_ARTICLE_LIKE';
export const GET_ARTICLES_BY_BOOKID = 'GET_ARTICLES_BY_BOOKID';
export const GET_ARTICLES_BY_USERID = 'GET_ARTICLES_BY_USERID';

export const POST_CURATION = 'POST_CURATION';
export const EDIT_CURATION = 'EDIT_CURATION';
export const GET_SPECIFIC_CURATION = 'GET_SPECIFIC_CURATION';
export const EDIT_SPECIFIC_CURATION = 'EDIT_SPECIFIC_CURATION';
export const DELETE_SPECIFIC_CURATION = 'DELETE_SPECIFIC_CURATION';
export const GET_CURATION_LIKE = 'GET_CURATION_LIKE';
export const POST_CURATION_LIKE = 'POST_CURATION_LIKE';
export const DELETE_CURATION_LIKE = 'DELETE_CURATION_LIKE';
export const GET_SEARCHED_CURATIONS = 'GET_SEARCHED_CURATIONS';
export const GET_CURATIONS_BY_USERID = 'GET_CURATIONS_BY_USERID';

export const POST_LONG_REVIEW_COMMENT = 'POST_LONG_REVIEW_COMMENT';
export const GET_SPECIFIC_LONG_REVIEW_COMMENT =
  'GET_SPECIFIC_LONG_REVIEW_COMMENT';
export const EDIT_SPECIFIC_LONG_REVIEW_COMMENT =
  'EDIT_SPECIFIC_LONG_REVIEW_COMMENT';
export const DELETE_SPECIFIC_LONG_REVIEW_COMMENT =
  'DELETE_SPECIFIC_LONG_REVIEW_COMMENT';
export const GET_COMMENTS_BY_REVIEWID = 'GET_COMMENTS_BY_REVIEWID';

export const GET_CURATIONS = 'GET_CURATIONS';
export const POST_CURATION_COMMENT = 'POST_CURATION_COMMENT';
export const GET_SPECIFIC_CURATION_COMMENT = 'GET_SPECIFIC_CURATION_COMMENT';
export const EDIT_SPECIFIC_CURATION_COMMENT = 'EDIT_SPECIFIC_CURATION_COMMENT';
export const DELETE_SPECIFIC_CURATION_COMMENT =
  'DELETE_SPECIFIC_CURATION_COMMENT';
export const GET_COMMENTS_BY_CURATIONID = 'GET_COMMENTS_BY_CURATIONID';

export const POST_LIBRARY = 'POST_LIBRARY';
export const GET_SPECIFIC_LIBRARY = 'GET_SPECIFIC_LIBRARY';
export const EDIT_SPECIFIC_LIBRARY = 'EDIT_SPECIFIC_LIBRARY';
export const DELETE_SPECIFIC_LIBRARY = 'DELETE_SPECIFIC_LIBRARY';
export const GET_LIBRARIES = 'GET_LIBRARIES';

export const FOLLOW_USER = 'FOLLOW_USER';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';
export const GET_FOLLOWS = 'GET_FOLLOWS';
export const GET_FOLLOWERS = 'GET_FOLLOWERS'; // DEPRICATED
export const GET_FOLLOWEES = 'GET_FOLLOWEES'; // DEPRICATED

export const EMPTY_SEARCHED_BOOKS = 'EMPTY_SEARCHED_BOOKS';
export const EMPTY_SELECTED_BOOK = 'EMPTY_SELECTED_BOOK';
export const RUN_OCR = 'RUN_OCR';
export const CLEAR_QUOTE = 'CLEAR_QUOTE';
export const UPLOAD_PROFILE_IMAGE = 'UPLOAD_PROFILE_IMAGE';

export const GET_ALARMS = 'GET_ALARMS';
export const TOGGLE_ALARM = 'TOGGLE_ALARM';
export const TOGGLE_ALARMS = 'TOGGLE_ALARMS';

export const GET_LIKED_BOOKS = 'GET_LIKED_BOOKS';
export const GET_BOOKMARKS = 'GET_BOOKMARKS';
export const GET_CURATION_BOOKMARKS = 'GET_CURATION_BOOKMARKS';
