matrix:
  include:
    - language: node_js
      node_js:
        - "10"
      dist: trusty
      addons:
        sonarcloud:
          organization: "swsnu"
          token:
            secure: "RnXCoy83suPhfDs8mMyHDoReMZekdF98mMNzQY/6kHKjYFY19HN/BcbBKr1hKTJm2fJs6pw86aXs35eiu4gGh1FBwfk2ZI+AKJHNY7Aqy/sor02Gw4UmgDVvt1/aQetlhvmyK3WuQMkeBd0mjTDV3A6LTbaUzpNQEzVkuESNJw4wXSakFsySnGyfbQCneklGtjwmS+HRxKTVzekc3AITArRUUt4OQruHxbgJmeB/IV42QpW63+k2XUf49JOBJ+1J53lcWcjdPPOH/WiV/Yum9KEWCOinHbIj1E1wVDwt6wiDVqNGrmA1KP/si1Y7BnBEOHBdS03OPDfzccw6n8Ue4J6BAfi0xMBc90Up9ou602JbxqxIBtFY9YW84nGpk8eSzTQvd6TRQw3oSbbz3z1Il+c8uGQEWClLbP/W3xKIBP+AVwR6VrOBmYjAY0XlOJ5xltOd0oXSpupKlAC4+8kXuEKLlTvqccBaFFaG78UWZvCb41OejneTiN9AQDaiy7Twi0m5/w3KmceGS6gfVEQZ5BgJZwJhmXMW422+1kQxebOzue2+WJTD8fIoe0mC+uLbRM1LwRXbPQuP16kxUTBQDk+YCleM4PtH9lN+VfSzatvVdF7t17u8WcerwFPExv++FQIrdJF5Qw7aB00wd47ZjEaafPjWjnYctolwzrqm7qA="
      before_install: # Script to run before install
        - cd booksbridge
      install: # Script to install required packages
        - yarn install
        - yarn add coveralls
      script: # Script to test your build
        - ./node_modules/.bin/eslint src
        - yarn test --coverage --watchAll=false
        - sonar-scanner
      after_success:
        - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

    - language: python
      python: 3.7.4
      dist: xenial
      # services:
      #   - mysql
      addons:
        sonarcloud:
          organization: "swsnu"
          token:
            secure: "RnXCoy83suPhfDs8mMyHDoReMZekdF98mMNzQY/6kHKjYFY19HN/BcbBKr1hKTJm2fJs6pw86aXs35eiu4gGh1FBwfk2ZI+AKJHNY7Aqy/sor02Gw4UmgDVvt1/aQetlhvmyK3WuQMkeBd0mjTDV3A6LTbaUzpNQEzVkuESNJw4wXSakFsySnGyfbQCneklGtjwmS+HRxKTVzekc3AITArRUUt4OQruHxbgJmeB/IV42QpW63+k2XUf49JOBJ+1J53lcWcjdPPOH/WiV/Yum9KEWCOinHbIj1E1wVDwt6wiDVqNGrmA1KP/si1Y7BnBEOHBdS03OPDfzccw6n8Ue4J6BAfi0xMBc90Up9ou602JbxqxIBtFY9YW84nGpk8eSzTQvd6TRQw3oSbbz3z1Il+c8uGQEWClLbP/W3xKIBP+AVwR6VrOBmYjAY0XlOJ5xltOd0oXSpupKlAC4+8kXuEKLlTvqccBaFFaG78UWZvCb41OejneTiN9AQDaiy7Twi0m5/w3KmceGS6gfVEQZ5BgJZwJhmXMW422+1kQxebOzue2+WJTD8fIoe0mC+uLbRM1LwRXbPQuP16kxUTBQDk+YCleM4PtH9lN+VfSzatvVdF7t17u8WcerwFPExv++FQIrdJF5Qw7aB00wd47ZjEaafPjWjnYctolwzrqm7qA="
      before_install:
        - cd booksbridge_backend
      install:
        - pip3 install -r requirements.txt
        - pip install coveralls
      script:
        - coverage run --branch --source='./book' manage.py test
        - coverage xml
        # - pylint ./*/
        - sonar-scanner
      after_success:
        - coveralls
