matrix:
  include:
    - language:
        - python # Your language e.g. node_js, python
      cache:
        yarn: true
        pip: true
      node_js:
        - "10" # node_js version
      python:
        - "3.6.8"
      dist: xenial
      services:
        - sqlite3
      addons:
        sonarcloud:
          organization: "swsnu"
          token:
            secure: "RnXCoy83suPhfDs8mMyHDoReMZekdF98mMNzQY/6kHKjYFY19HN/BcbBKr1hKTJm2fJs6pw86aXs35eiu4gGh1FBwfk2ZI+AKJHNY7Aqy/sor02Gw4UmgDVvt1/aQetlhvmyK3WuQMkeBd0mjTDV3A6LTbaUzpNQEzVkuESNJw4wXSakFsySnGyfbQCneklGtjwmS+HRxKTVzekc3AITArRUUt4OQruHxbgJmeB/IV42QpW63+k2XUf49JOBJ+1J53lcWcjdPPOH/WiV/Yum9KEWCOinHbIj1E1wVDwt6wiDVqNGrmA1KP/si1Y7BnBEOHBdS03OPDfzccw6n8Ue4J6BAfi0xMBc90Up9ou602JbxqxIBtFY9YW84nGpk8eSzTQvd6TRQw3oSbbz3z1Il+c8uGQEWClLbP/W3xKIBP+AVwR6VrOBmYjAY0XlOJ5xltOd0oXSpupKlAC4+8kXuEKLlTvqccBaFFaG78UWZvCb41OejneTiN9AQDaiy7Twi0m5/w3KmceGS6gfVEQZ5BgJZwJhmXMW422+1kQxebOzue2+WJTD8fIoe0mC+uLbRM1LwRXbPQuP16kxUTBQDk+YCleM4PtH9lN+VfSzatvVdF7t17u8WcerwFPExv++FQIrdJF5Qw7aB00wd47ZjEaafPjWjnYctolwzrqm7qA="
      before_install: # Script to run before install
      #- cd booksbridge
      install: # Script to install required packages
        - cd booksbridge
        - yarn install
        - yarn add coveralls
        - cd ..
        - cd booksbridge_backend
        - pip3 install -r requirements.txt
        - pip install coveralls
        - cd ..
      script: # Script to test your build
        - cd booksbridge
        - ./node_modules/.bin/eslint src
        - yarn test --coverage --watchAll=false
        - cd ..
        - cd booksbridge_backend
        - coverage run --branch --source='./book' manage.py test
        - coverage report
        - coverage html
        - cd ..
        - sonar-scanner
      after_success:
        - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
