# Generated by Django 2.2.5 on 2019-10-30 14:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='NO TITLE')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_long', models.BooleanField(default=False)),
                ('is_short', models.BooleanField(default=False)),
                ('is_phrase', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='longreview',
            name='author',
        ),
        migrations.RemoveField(
            model_name='longreview',
            name='book',
        ),
        migrations.RemoveField(
            model_name='phrase',
            name='author',
        ),
        migrations.RemoveField(
            model_name='phrase',
            name='book',
        ),
        migrations.RemoveField(
            model_name='phraselike',
            name='phrase',
        ),
        migrations.RemoveField(
            model_name='phraselike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shortreview',
            name='author',
        ),
        migrations.RemoveField(
            model_name='shortreview',
            name='book',
        ),
        migrations.RemoveField(
            model_name='shortreviewlike',
            name='short_reiew',
        ),
        migrations.RemoveField(
            model_name='shortreviewlike',
            name='user',
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='longreivewcomment',
            name='long_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Article'),
        ),
        migrations.DeleteModel(
            name='LongReivewLike',
        ),
        migrations.DeleteModel(
            name='LongReview',
        ),
        migrations.DeleteModel(
            name='Phrase',
        ),
        migrations.DeleteModel(
            name='PhraseLike',
        ),
        migrations.DeleteModel(
            name='ShortReview',
        ),
        migrations.DeleteModel(
            name='ShortReviewLike',
        ),
        migrations.AddField(
            model_name='article',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book'),
        ),
    ]
